# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI - HEX -master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  first:
     runs-on: ubuntu-latest
     steps:
   
       - uses: actions/checkout@v2
       - name: Set up JDK ${{ matrix.java }}
         uses: actions/setup-java@v1
         with:
          java-version: 1.11
       - name: Build with Gradle
         run: ./gradlew build -x test

  sonarQube:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew build test
      - name: Build with Gradle
        run: ./gradlew jacocoMergeTest
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        run: ./gradlew sonarqube

  build:
    needs: [first]

    strategy:
      matrix:
        name: [linux, windows]
        include:
          - name: linux
            os: ubuntu-latest
            java: 1.11
          - name: windows
            os: windows-latest
            java: 1.8

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
          with:
                fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: get jar application
        uses: actions/upload-artifact@v1
        with:
          name: app-full-${{ matrix.os }}-jdk-${{ matrix.java }}
          path: application/build/libs
      - name: get jar simple-delivery
        uses: actions/upload-artifact@v1
        with:
          name: delivery-${{ matrix.os }}-jdk-${{ matrix.java }}
          path: delivery-app/delivery-docker/build/libs
#      - name: get jar app-full
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-full-${{ matrix.os }}-jdk-${{ matrix.java }}
#          path: /application/build/libs
      - name: get jar food-order
        uses: actions/upload-artifact@v1
        with:
          name: food-order-${{ matrix.os }}-jdk-${{ matrix.java }}
          path: food-order-app/food-order-docker/build/libs
      - name: get jar restaurant
        uses: actions/upload-artifact@v1
        with:
          name: restaurant-${{ matrix.os }}-jdk-${{ matrix.java }}
          path: restaurant-app/restaurant-docker/build/libs
