# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI - HEX -master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  first:
     runs-on: ubuntu-latest
     steps:
   
       - uses: actions/checkout@v2
       - name: Set up JDK ${{ matrix.java }}
         uses: actions/setup-java@v1
         with:
          java-version: 1.11
       - name: Build with Gradle
         run: ./gradlew test


  build:
    needs: [first]

    strategy:
      matrix:
        name: [linux, windows]
        include:
          - name: linux
            os: ubuntu-latest
            java: 1.8
          - name: windows
            os: windows-latest
            java: 1.11

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

 #     - name: ls -a
 #       run: ls -a
      - name: git log -5
        run: git log 
#       - name: Grant execute permission for gradlew
#         if: startsWith(matrix.os, 'ubuntu-latest')
#         run: chmod +x gradlew
#         run : chmod +x gradlew
#        run: git update-index --chmod=+x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: get jar
        uses: actions/upload-artifact@v1
        with:
          name: jar-${{ matrix.os }}-${{ matrix.java }}
          path: build/libs/mija-hex.jar
